MUS-20 유저 신고 도메인 관리자 검토 비즈니스 로직 개발
MarkJun-Project/music-site-api pull request #16
Opened 2024-10-07 13:32 UTC by byeonguk2

2024-10-07 13:40 UTC, MarkJunHyeok requested changes
코멘트 확인해주세요

2024-10-07 13:40 UTC, MarkJunHyeok commented on common/src/main/java/com/music/common/report/domain/Report.java
> +    public void startAdminReview(Admin admin) {
1. 함수명은 동사로 하는게 좋아보입니다.
2. Admin명사가 들어갈 이유가 없어보입니다. (콩글리쉬)

따라서 startReview가 더 좋아보입니다.

2024-10-07 13:40 UTC, MarkJunHyeok commented on common/src/main/java/com/music/common/report/domain/Report.java
> +        require(nonNull(admin));
검증과 변수할당은 서로 목적? 주제?가 다르니 개행을 추가하심이 좋아보이네요

2024-10-07 13:40 UTC, MarkJunHyeok commented on common/src/main/java/com/music/common/report/domain/Report.java
> +    public void startAdminReview(Admin admin) {
해당 함수에서 상태에 따라서 이미 처리된 경우 혹은 처리할 수 없는 상황일 때는
check() 함수를 통해서 검증을 하여 처리가 안되도록 보호 로직을 작성할 필요가 있어보입니다.

2024-10-07 14:59 UTC, byeonguk2 commented on common/src/main/java/com/music/common/report/domain/Report.java
> +    public void startAdminReview(Admin admin) {
신고 검토전 상태인지 검증하는 로직과 admin이 null이 아닌지 검증하는 로직을 validateBeforeReview 이라는 함수로 따로 분리하였습니다.

2024-10-07 14:59 UTC, byeonguk2 commented on common/src/main/java/com/music/common/report/domain/Report.java
> +        require(nonNull(admin));
검증 함수로 분리하였습니다.

2024-10-08 00:05 UTC, MarkJunHyeok commented on common/src/main/java/com/music/common/report/domain/Report.java
> +    public void startAdminReview(Admin admin) {
check() 함수가 따로 존재합니다.
Preconditions 클래스 확인해주세요

2024-10-08 00:06 UTC, MarkJunHyeok commented on common/src/main/java/com/music/common/report/domain/Report.java
> +        require(nonNull(admin));
개행은 그냥 줄바꿈 하나 추가하란 말씀이었습니다.

2024-10-08 02:28 UTC, byeonguk2 commented on common/src/main/java/com/music/common/report/domain/Report.java
> +        require(nonNull(admin));
변경했습니다.

2024-10-08 02:28 UTC, byeonguk2 commented on common/src/main/java/com/music/common/report/domain/Report.java
> +    public void startAdminReview(Admin admin) {
확인하여 변경했습니다.

2024-10-08 03:16 UTC, MarkJunHyeok approved these changes
수고하셨습니다.

2024-10-09 13:30 UTC, yookyungmin approved these changes

2024-10-10 08:32 UTC, merged