MUS-21 첨부파일 로컬 업로드 로직 개발
MarkJun-Project/music-site-api pull request #18
Opened 2024-10-08 09:59 UTC by byeonguk2

2024-10-09 13:33 UTC, yookyungmin approved these changes

2024-10-10 09:24 UTC, byeonguk2 commented
integraion.yml 파일에 환경변수를 추가하여 수정했습니다.

2024-10-11 04:19 UTC, MarkJunHyeok requested changes
코멘트 확인 부탁드립니다.

2024-10-11 04:19 UTC, MarkJunHyeok commented on integration/src/main/java/com/music/integration/storege/LocalFileStore.java
> +public class LocalFileStore implements FileStore{
@Profile 도 따로 지정이 안되어 있는것으로 보아 실제 운영서버 혹은 데브서버에서도 사용할 수 있도록 구현한 클래스가 아닌가요? 하지만 그렇다기엔 LocalFileStore라는 작명은 적합하지 않아보이는데 하신 이유가 궁금합니다.

2024-10-11 07:00 UTC, byeonguk2 commented on integration/src/main/java/com/music/integration/storege/LocalFileStore.java
> +public class LocalFileStore implements FileStore{
LocalFileStore라는 이름은 로컬 환경을 뜻하는 것이 아니라, 컴퓨터 내부의 로컬 저장소에 파일이 저장된다는 의미로 지었습니다. 그러나 이 이름이 다소 모호하게 느껴질 수 있어, 다른 작명으로 변경하겠습니다.

2024-10-11 07:53 UTC, byeonguk2 commented on integration/src/main/java/com/music/integration/storege/LocalFileStore.java
> +public class LocalFileStore implements FileStore{
DefaultFileStore 라는 이름으로 변경했습니다.

2024-10-12 02:11 UTC, MarkJunHyeok approved these changes
아직 실제로 저장되는 구현부를 못봐서 아쉬운 PR이긴하지만 추후에 작업하면서 수정해나가면 되보입니다.

수고하셨습니다.

2024-10-12 03:21 UTC, merged