MUS-26 댓글 도메인 서비스 생성 개발
MarkJun-Project/music-site-api pull request #25
Opened 2024-10-11 15:41 UTC by yookyungmin

2024-10-12 01:38 UTC, MarkJunHyeok requested changes
코멘트 확인 바랍니다.

2024-10-12 01:38 UTC, MarkJunHyeok commented on common/src/test/java/com/music/common/comment/service/DomainCommentServiceTest.java
> +        board = boardRepository.save(boardService.create(
Fixture 를 사용해주세요 함수가 없다면 하나 추가로 정의해주세요

2024-10-12 01:38 UTC, MarkJunHyeok commented on common/src/test/java/com/music/common/comment/service/DomainCommentServiceTest.java
> +        //board = boardRepository.save(BoardFixture.create());
의미없는 주석은 지워주세요

2024-10-12 14:58 UTC, byeonguk2 approved these changes

2024-10-12 14:58 UTC, byeonguk2 commented on common/src/test/java/com/music/common/comment/service/DomainCommentServiceTest.java
> +        assertThat(comment.getComment()).isEqualTo("comment");
게시물,유저 아이디가 잘 저장되어 있는지 검증하는 것도 있으면 좋을 거 같아요!

2024-10-13 06:24 UTC, yookyungmin commented on common/src/test/java/com/music/common/comment/service/DomainCommentServiceTest.java
> +        assertThat(comment.getComment()).isEqualTo("comment");
넵

2024-10-13 06:24 UTC, yookyungmin commented on common/src/test/java/com/music/common/comment/service/DomainCommentServiceTest.java
> +        board = boardRepository.save(boardService.create(
수정했습니다!

2024-10-13 06:24 UTC, yookyungmin commented on common/src/test/java/com/music/common/comment/service/DomainCommentServiceTest.java
> +        //board = boardRepository.save(BoardFixture.create());
수정했습니다

2024-10-13 06:34 UTC, yookyungmin reviewed
게시물, 유저 검증추가 했습니다!

2024-10-13 06:39 UTC, byeonguk2 commented
수고하셨습니당

2024-10-13 12:47 UTC, MarkJunHyeok requested changes
코멘트 확인 부탁드립니다.

2024-10-13 12:47 UTC, MarkJunHyeok commented on common/src/test/java/com/music/common/comment/service/DomainCommentServiceTest.java
> +//
의미없는 주석일까요?

2024-10-13 13:01 UTC, yookyungmin commented on common/src/test/java/com/music/common/comment/service/DomainCommentServiceTest.java
> +//
수정 했습니다

2024-10-14 00:48 UTC, MarkJunHyeok approved these changes
수고하셨습니다.

2024-10-14 11:52 UTC, merged