MUS-33 게시글 앱 서비스 첨부파일 업로드 개발
MarkJun-Project/music-site-api pull request #30
Opened 2024-10-13 08:27 UTC by byeonguk2

2024-10-13 12:44 UTC, yookyungmin approved these changes

2024-10-15 00:09 UTC, MarkJunHyeok requested changes
코멘트 확인해주세요

2024-10-15 00:09 UTC, MarkJunHyeok commented on api/src/main/java/com/music/core/service/board/DefaultBoardAppService.java
> +        val uploadFile = fileStore.upload(multipartFile, Board.DIR_NAME);
개행 추가해주세요

2024-10-15 09:42 UTC, byeonguk2 commented on api/src/main/java/com/music/core/service/board/DefaultBoardAppService.java
> +        val uploadFile = fileStore.upload(multipartFile, Board.DIR_NAME);
추가했습니다.

2024-10-15 10:01 UTC, MarkJunHyeok approved these changes
수고하셨습니다!

2024-10-15 10:13 UTC, merged