MUS-35 팔로우 도메인 서비스 생성 개발
MarkJun-Project/music-site-api pull request #34
Opened 2024-10-15 11:35 UTC by byeonguk2

2024-10-15 14:18 UTC, yookyungmin approved these changes

2024-10-16 00:09 UTC, MarkJunHyeok requested changes
코멘트 확인 부탁드립니다.

2024-10-16 00:09 UTC, MarkJunHyeok commented on common/src/main/java/com/music/common/follow/domain/FollowRepository.java
> +    boolean existsByFollowerIdAndFolloweeId(Long followerId, Long followeeId);
해당 레포지토리 테스트도 있으면 좋아보입니다.

2024-10-19 04:20 UTC, byeonguk2 commented on common/src/main/java/com/music/common/follow/domain/FollowRepository.java
> +    boolean existsByFollowerIdAndFolloweeId(Long followerId, Long followeeId);
추가 했습니다.

2024-10-20 07:01 UTC, yookyungmin approved these changes

2024-10-21 01:30 UTC, MarkJunHyeok approved these changes
수고하셨습니다.

2024-10-21 04:50 UTC, merged