MUS-12 알림 도메인 설계 및 생성 로직 개발
MarkJun-Project/music-site-api pull request #9
Opened 2024-09-30 12:05 UTC by byeonguk2

Comment 도메인을 아직 설계하지 못해서 추후에 도메인 설계를 완료한 후 알림을 추가하겠습니다.

2024-10-02 09:12 UTC, MarkJunHyeok requested changes

2024-10-02 09:12 UTC, MarkJunHyeok commented on common/src/main/java/com/music/common/notifications/domain/BoardNotifications.java
> +@DiscriminatorValue("B")
@DiscriminatorValue 어노테이션을 명시한 이유가 있을까요?

2024-10-02 09:12 UTC, MarkJunHyeok commented on common/src/main/java/com/music/common/notifications/domain/FollowNotifications.java
> +@DiscriminatorValue("F")
마찬가지.

2024-10-02 09:12 UTC, MarkJunHyeok commented on common/src/main/java/com/music/common/notifications/domain/LikesNotifications.java
> +@DiscriminatorValue("L")
22

2024-10-02 09:12 UTC, MarkJunHyeok commented on common/src/main/java/com/music/common/notifications/domain/Notifications.java
> +@DiscriminatorColumn(name = "DTYPE")
22

2024-10-02 09:12 UTC, MarkJunHyeok commented on common/src/main/java/com/music/common/notifications/domain/NotificationsType.java
> +    NEW_BOARD, NEW_FOLLOW, NEW_LIKE, CANCEL_FOLLOW
DType으로 하위 클래스에서 타입이 구분될 것으로 보이는데 해당 타입이 따로 필요한 이유가 있을까요

2024-10-06 07:56 UTC, byeonguk2 commented on common/src/main/java/com/music/common/notifications/domain/BoardNotifications.java
> +@DiscriminatorValue("B")
서브 타입을 구분하려고 했습니다. 
기본값으로 사용하여도 괜찮을거 같아서 수정했습니다.

2024-10-06 07:56 UTC, byeonguk2 commented on common/src/main/java/com/music/common/notifications/domain/FollowNotifications.java
> +@DiscriminatorValue("F")
위 내용과 마찬가지로 기본값으로 수정했습니다.

2024-10-06 07:56 UTC, byeonguk2 commented on common/src/main/java/com/music/common/notifications/domain/LikesNotifications.java
> +@DiscriminatorValue("L")
위 내용과 마찬가지로 기본값으로 수정했습니다.

2024-10-06 07:57 UTC, byeonguk2 commented on common/src/main/java/com/music/common/notifications/domain/Notifications.java
> +@DiscriminatorColumn(name = "DTYPE")
기본값으로 수정하였습니다.

2024-10-06 07:57 UTC, byeonguk2 commented on common/src/main/java/com/music/common/notifications/domain/NotificationsType.java
> +    NEW_BOARD, NEW_FOLLOW, NEW_LIKE, CANCEL_FOLLOW
DTYPE으로 구분하게 변경하고 해당 enum 클래스 삭제했습니다.

2024-10-06 15:35 UTC, MarkJunHyeok requested changes
코멘트 확인 부탁드립니다.

2024-10-06 15:35 UTC, MarkJunHyeok commented on common/src/main/java/com/music/common/notifications/domain/Notifications.java
> +    private boolean isRead = false;
사용자 페이지 기준에서 사용자가 알림을 읽은 후 삭제를 할수도 있을 것 같은데 CREATED, READED, DELETED 이런 상태로 구분하는것이 어떨까요?

2024-10-07 07:52 UTC, byeonguk2 commented on common/src/main/java/com/music/common/notifications/domain/Notifications.java
> +    private boolean isRead = false;
NotificationsStatus Enum 클래스를 추가하여 status라는 필드로 변경하였습니다.

2024-10-07 07:52 UTC, MarkJunHyeok approved these changes
수고하셨습니다.

2024-10-07 08:17 UTC, merged